// <auto-generated />
using System;
using CarBook.Persistence.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace CarBook.Persistence.Migrations
{
    [DbContext(typeof(CarBookContext))]
    [Migration("20250106082534_SeedDataReservationStatus")]
    partial class SeedDataReservationStatus
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("CarBook.Domain.Entities.About", b =>
                {
                    b.Property<int>("AboutId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AboutId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AboutId");

                    b.ToTable("Abouts");

                    b.HasData(
                        new
                        {
                            AboutId = 1,
                            Description = "CarBook, araç kiralama sektöründe en iyi hizmeti sunmak için kendini sürekli geliştiren bir platformdur. Modern teknoloji ile hızlı ve kolay araç kiralama imkanı sunarken, geniş araç yelpazesiyle her ihtiyaca uygun seçenekler sağlar. Müşteri memnuniyetini ön planda tutarak, güvenli ve pratik bir kiralama deneyimi sunuyoruz.",
                            ImageUrl = "/carbook-master/images/bg_3.jpg",
                            Title = "CarBook'a Hoş Geldiniz! Yola Çıkmaya Hazır Mısınız ?"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Author", b =>
                {
                    b.Property<int>("AuthorId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AuthorId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AuthorId");

                    b.ToTable("Authors");

                    b.HasData(
                        new
                        {
                            AuthorId = 1,
                            Description = "Deneyimli bir otomobil meraklısı ve blog yazarı.",
                            ImageUrl = "/carbook-master/images/Person_3.jpg",
                            Name = "Ahmet Yılmaz"
                        },
                        new
                        {
                            AuthorId = 2,
                            Description = "Otomobil endüstrisinde uzmanlaşmış bir mühendis.",
                            ImageUrl = "/carbook-master/images/Person_2.jpg",
                            Name = "Mehmet Ak"
                        },
                        new
                        {
                            AuthorId = 3,
                            Description = "Araç incelemeleri ve test sürüşleri konusunda uzman.",
                            ImageUrl = "/carbook-master/images/Person_1.jpg",
                            Name = "Mustafa Çelik"
                        },
                        new
                        {
                            AuthorId = 4,
                            Description = "Otomobil teknolojileri ve yenilikler konusunda bilgili bir gazeteci.",
                            ImageUrl = "/carbook-master/images/Person_2.jpg",
                            Name = "Ali Vural"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Banner", b =>
                {
                    b.Property<int>("BannerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BannerId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("VideoUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BannerId");

                    b.ToTable("Banners");

                    b.HasData(
                        new
                        {
                            BannerId = 1,
                            Description = "CarBook ile 7/24 kolay ve hızlı araç kiralama! Geniş araç seçenekleri, uygun fiyatlar ve kesintisiz hizmetle dilediğiniz zaman aracınızı kiralayın.",
                            Title = "Kolay Ve Hızlı Araç Kiralayın",
                            VideoDescription = "Tanıtım Videosu",
                            VideoUrl = "https://www.youtube.com/watch?v=ZlaVqOI3cCQ"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Blog", b =>
                {
                    b.Property<int>("BlogId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BlogId"));

                    b.Property<int>("AuthorID")
                        .HasColumnType("int");

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BlogId");

                    b.HasIndex("AuthorID");

                    b.HasIndex("CategoryId");

                    b.ToTable("Blogs");

                    b.HasData(
                        new
                        {
                            BlogId = 1,
                            AuthorID = 1,
                            CategoryId = 4,
                            CoverImageUrl = "/carbook-master/images/bg_3.jpg",
                            CreatedDate = new DateTime(2023, 6, 15, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Elektrikli araçların geleceği ve çevre üzerindeki etkileri hakkında bilgi veren bir yazı.",
                            Title = "Elektrikli Araçların Geleceği"
                        },
                        new
                        {
                            BlogId = 2,
                            AuthorID = 2,
                            CategoryId = 2,
                            CoverImageUrl = "/carbook-master/images/image_1.jpg",
                            CreatedDate = new DateTime(2023, 7, 20, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "SUV araçlarının sağladığı avantajlar ve neden tercih edildikleri üzerine bir yazı.",
                            Title = "SUV Modellerinin Avantajları"
                        },
                        new
                        {
                            BlogId = 3,
                            AuthorID = 3,
                            CategoryId = 1,
                            CoverImageUrl = "/carbook-master/images/image_2.jpg",
                            CreatedDate = new DateTime(2023, 8, 10, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Sedan araba modellerinin konfor ve performans açısından sundukları özellikler.",
                            Title = "Sedan Arabalar: Konfor ve Performans"
                        },
                        new
                        {
                            BlogId = 4,
                            AuthorID = 4,
                            CategoryId = 3,
                            CoverImageUrl = "/carbook-master/images/image_3.jpg",
                            CreatedDate = new DateTime(2023, 9, 5, 0, 0, 0, 0, DateTimeKind.Unspecified),
                            Description = "Kamyonların güçlü motor yapıları ve dayanıklılıkları üzerine detaylı bir yazı.",
                            Title = "Kamyonların Dayanıklılığı ve Gücü"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Brand", b =>
                {
                    b.Property<int>("BrandId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BrandId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("BrandId");

                    b.ToTable("Brands");

                    b.HasData(
                        new
                        {
                            BrandId = 1,
                            Name = "Mercedes"
                        },
                        new
                        {
                            BrandId = 2,
                            Name = "Range Rover"
                        },
                        new
                        {
                            BrandId = 3,
                            Name = "BMW"
                        },
                        new
                        {
                            BrandId = 4,
                            Name = "Audi"
                        },
                        new
                        {
                            BrandId = 5,
                            Name = "Renault"
                        },
                        new
                        {
                            BrandId = 6,
                            Name = "Volkswogen"
                        },
                        new
                        {
                            BrandId = 7,
                            Name = "Toyota"
                        },
                        new
                        {
                            BrandId = 8,
                            Name = "Jeep"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Car", b =>
                {
                    b.Property<int>("CarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarId"));

                    b.Property<string>("BigImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("BrandId")
                        .HasColumnType("int");

                    b.Property<string>("CoverImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Fuel")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Km")
                        .HasColumnType("int");

                    b.Property<byte>("Luggage")
                        .HasColumnType("tinyint");

                    b.Property<string>("Model")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<byte>("Seat")
                        .HasColumnType("tinyint");

                    b.Property<string>("Transmission")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarId");

                    b.HasIndex("BrandId");

                    b.ToTable("Cars");

                    b.HasData(
                        new
                        {
                            CarId = 1,
                            BigImageUrl = "/carbook-master/images/car-1.jpg",
                            BrandId = 1,
                            CoverImageUrl = "/carbook-master/images/car-1.jpg",
                            Fuel = "Benzin",
                            Km = 5000,
                            Luggage = (byte)2,
                            Model = "E-200",
                            Seat = (byte)5,
                            Transmission = "Otomatik"
                        },
                        new
                        {
                            CarId = 2,
                            BigImageUrl = "/carbook-master/images/car-2.jpg",
                            BrandId = 2,
                            CoverImageUrl = "/carbook-master/images/car-2.jpg",
                            Fuel = "Dizel",
                            Km = 12000,
                            Luggage = (byte)3,
                            Model = "Velar",
                            Seat = (byte)5,
                            Transmission = "Otomatik"
                        },
                        new
                        {
                            CarId = 3,
                            BigImageUrl = "/carbook-master/images/car-5.jpg",
                            BrandId = 3,
                            CoverImageUrl = "/carbook-master/images/car-5.jpg",
                            Fuel = "Elektrik",
                            Km = 8000,
                            Luggage = (byte)2,
                            Model = "BMW Serisi",
                            Seat = (byte)5,
                            Transmission = "Manuel"
                        },
                        new
                        {
                            CarId = 4,
                            BigImageUrl = "/carbook-master/images/car-12.jpg",
                            BrandId = 4,
                            CoverImageUrl = "/carbook-master/images/car-12.jpg",
                            Fuel = "Benzin",
                            Km = 15000,
                            Luggage = (byte)1,
                            Model = "A3",
                            Seat = (byte)4,
                            Transmission = "Manuel"
                        },
                        new
                        {
                            CarId = 5,
                            BigImageUrl = "/carbook-master/images/car-4.jpg",
                            BrandId = 5,
                            CoverImageUrl = "/carbook-master/images/car-4.jpg",
                            Fuel = "Dizel",
                            Km = 3000,
                            Luggage = (byte)1,
                            Model = "Clio",
                            Seat = (byte)5,
                            Transmission = "Manuel"
                        },
                        new
                        {
                            CarId = 6,
                            BigImageUrl = "/carbook-master/images/car-3.jpg",
                            BrandId = 6,
                            CoverImageUrl = "/carbook-master/images/car-3.jpg",
                            Fuel = "Elektrik",
                            Km = 10000,
                            Luggage = (byte)3,
                            Model = "Passat",
                            Seat = (byte)5,
                            Transmission = "Otomatik"
                        },
                        new
                        {
                            CarId = 7,
                            BigImageUrl = "/carbook-master/images/car-6.jpg",
                            BrandId = 7,
                            CoverImageUrl = "/carbook-master/images/car-6.jpg",
                            Fuel = "Dizel",
                            Km = 20000,
                            Luggage = (byte)2,
                            Model = "Corolla",
                            Seat = (byte)5,
                            Transmission = "Manuel"
                        },
                        new
                        {
                            CarId = 8,
                            BigImageUrl = "/carbook-master/images/car-8.jpg",
                            BrandId = 8,
                            CoverImageUrl = "/carbook-master/images/car-8.jpg",
                            Fuel = "Benzin",
                            Km = 15000,
                            Luggage = (byte)2,
                            Model = "Cherokee",
                            Seat = (byte)5,
                            Transmission = "Otomatik"
                        },
                        new
                        {
                            CarId = 9,
                            BigImageUrl = "/carbook-master/images/car-7.jpg",
                            BrandId = 1,
                            CoverImageUrl = "/carbook-master/images/car-7.jpg",
                            Fuel = "Dizel",
                            Km = 18000,
                            Luggage = (byte)3,
                            Model = "S 350 BlueTEC 4Matic",
                            Seat = (byte)5,
                            Transmission = "Otomatik"
                        },
                        new
                        {
                            CarId = 10,
                            BigImageUrl = "/carbook-master/images/car-9.jpg",
                            BrandId = 1,
                            CoverImageUrl = "/carbook-master/images/car-9.jpg",
                            Fuel = "Dizel",
                            Km = 22000,
                            Luggage = (byte)2,
                            Model = "S 320 CDI",
                            Seat = (byte)5,
                            Transmission = "Manuel"
                        },
                        new
                        {
                            CarId = 11,
                            BigImageUrl = "/carbook-master/images/car-10.jpg",
                            BrandId = 1,
                            CoverImageUrl = "/carbook-master/images/car-10.jpg",
                            Fuel = "Elektrik",
                            Km = 5000,
                            Luggage = (byte)3,
                            Model = "S 400 400",
                            Seat = (byte)5,
                            Transmission = "Otomatik"
                        },
                        new
                        {
                            CarId = 12,
                            BigImageUrl = "/carbook-master/images/car-11.jpg",
                            BrandId = 1,
                            CoverImageUrl = "/carbook-master/images/car-11.jpg",
                            Fuel = "Benzin",
                            Km = 12000,
                            Luggage = (byte)2,
                            Model = "S 500 500 L",
                            Seat = (byte)5,
                            Transmission = "Manuel"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.CarDescription", b =>
                {
                    b.Property<int>("CarDescriptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarDescriptionId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CarDescriptionId");

                    b.HasIndex("CarId");

                    b.ToTable("CarDescriptions");

                    b.HasData(
                        new
                        {
                            CarDescriptionId = 1,
                            CarId = 1,
                            Details = "Mercedes E-200, şık ve güçlü bir sedan modelidir. Benzinli motoru, yüksek konforu ve zarif tasarımı ile öne çıkar."
                        },
                        new
                        {
                            CarDescriptionId = 2,
                            CarId = 2,
                            Details = "Range Rover Velar, lüks SUV sınıfında yer alır. Şık tasarımı, güçlü motoru ve 4x4 özellikleriyle dikkat çeker."
                        },
                        new
                        {
                            CarDescriptionId = 3,
                            CarId = 3,
                            Details = "BMW Serisi, dinamik sürüş deneyimi sunar. Modern tasarımı ve premium özellikleriyle uzun yolculuklarda konfor sağlar."
                        },
                        new
                        {
                            CarDescriptionId = 4,
                            CarId = 4,
                            Details = "Audi A3, kompakt sınıfta lüks bir seçenektir. Güçlü motorları ve şık tasarımı ile şehir içi kullanım için ideal."
                        },
                        new
                        {
                            CarDescriptionId = 5,
                            CarId = 5,
                            Details = "Renault Clio, ekonomik bir hatchback modelidir. Kompakt yapısı, pratikliği ve düşük yakıt tüketimi ile şehir içi kullanımda tercih edilir."
                        },
                        new
                        {
                            CarDescriptionId = 6,
                            CarId = 6,
                            Details = "Volkswogen Passat, orta sınıf sedan bir araçtır. Geniş iç hacmi ve sağlam yapısıyla uzun yolculuklar için idealdir."
                        },
                        new
                        {
                            CarDescriptionId = 7,
                            CarId = 7,
                            Details = "Toyota Corolla, güvenli ve dayanıklı bir sedan modelidir. Düşük bakım maliyetleri ve ekonomik yakıt tüketimi ile öne çıkar."
                        },
                        new
                        {
                            CarDescriptionId = 8,
                            CarId = 8,
                            Details = "Jeep Cherokee, arazi yetenekleri ile öne çıkan bir SUV'dur. Hem şehir içinde hem de zorlu yol koşullarında güçlü performans sergiler."
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.CarFeature", b =>
                {
                    b.Property<int>("CarFeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarFeatureId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("FeatureId")
                        .HasColumnType("int");

                    b.HasKey("CarFeatureId");

                    b.HasIndex("CarId");

                    b.HasIndex("FeatureId");

                    b.ToTable("CarFeatures");

                    b.HasData(
                        new
                        {
                            CarFeatureId = 1,
                            Available = true,
                            CarId = 1,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 2,
                            Available = true,
                            CarId = 1,
                            FeatureId = 2
                        },
                        new
                        {
                            CarFeatureId = 3,
                            Available = true,
                            CarId = 1,
                            FeatureId = 3
                        },
                        new
                        {
                            CarFeatureId = 4,
                            Available = false,
                            CarId = 1,
                            FeatureId = 4
                        },
                        new
                        {
                            CarFeatureId = 5,
                            Available = true,
                            CarId = 2,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 6,
                            Available = true,
                            CarId = 2,
                            FeatureId = 2
                        },
                        new
                        {
                            CarFeatureId = 7,
                            Available = true,
                            CarId = 2,
                            FeatureId = 5
                        },
                        new
                        {
                            CarFeatureId = 8,
                            Available = true,
                            CarId = 3,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 9,
                            Available = true,
                            CarId = 3,
                            FeatureId = 6
                        },
                        new
                        {
                            CarFeatureId = 10,
                            Available = true,
                            CarId = 4,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 11,
                            Available = true,
                            CarId = 4,
                            FeatureId = 3
                        },
                        new
                        {
                            CarFeatureId = 12,
                            Available = false,
                            CarId = 4,
                            FeatureId = 8
                        },
                        new
                        {
                            CarFeatureId = 13,
                            Available = true,
                            CarId = 5,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 14,
                            Available = true,
                            CarId = 5,
                            FeatureId = 2
                        },
                        new
                        {
                            CarFeatureId = 15,
                            Available = true,
                            CarId = 6,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 16,
                            Available = true,
                            CarId = 6,
                            FeatureId = 3
                        },
                        new
                        {
                            CarFeatureId = 17,
                            Available = true,
                            CarId = 7,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 18,
                            Available = false,
                            CarId = 7,
                            FeatureId = 4
                        },
                        new
                        {
                            CarFeatureId = 19,
                            Available = true,
                            CarId = 8,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 20,
                            Available = true,
                            CarId = 8,
                            FeatureId = 5
                        },
                        new
                        {
                            CarFeatureId = 21,
                            Available = true,
                            CarId = 9,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 22,
                            Available = true,
                            CarId = 9,
                            FeatureId = 6
                        },
                        new
                        {
                            CarFeatureId = 23,
                            Available = true,
                            CarId = 10,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 24,
                            Available = true,
                            CarId = 10,
                            FeatureId = 3
                        },
                        new
                        {
                            CarFeatureId = 25,
                            Available = true,
                            CarId = 11,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 26,
                            Available = true,
                            CarId = 11,
                            FeatureId = 4
                        },
                        new
                        {
                            CarFeatureId = 27,
                            Available = true,
                            CarId = 12,
                            FeatureId = 1
                        },
                        new
                        {
                            CarFeatureId = 28,
                            Available = true,
                            CarId = 12,
                            FeatureId = 8
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.CarPricing", b =>
                {
                    b.Property<int>("CarPricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CarPricingId"));

                    b.Property<decimal>("Amount")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("PricingId")
                        .HasColumnType("int");

                    b.HasKey("CarPricingId");

                    b.HasIndex("CarId");

                    b.HasIndex("PricingId");

                    b.ToTable("CarPricings");

                    b.HasData(
                        new
                        {
                            CarPricingId = 1,
                            Amount = 100m,
                            CarId = 1,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 2,
                            Amount = 900m,
                            CarId = 1,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 3,
                            Amount = 6000m,
                            CarId = 1,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 4,
                            Amount = 20000m,
                            CarId = 1,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 5,
                            Amount = 110m,
                            CarId = 2,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 6,
                            Amount = 950m,
                            CarId = 2,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 7,
                            Amount = 6300m,
                            CarId = 2,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 8,
                            Amount = 21000m,
                            CarId = 2,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 9,
                            Amount = 120m,
                            CarId = 3,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 10,
                            Amount = 1000m,
                            CarId = 3,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 11,
                            Amount = 7000m,
                            CarId = 3,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 12,
                            Amount = 23000m,
                            CarId = 3,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 13,
                            Amount = 130m,
                            CarId = 4,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 14,
                            Amount = 1050m,
                            CarId = 4,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 15,
                            Amount = 7350m,
                            CarId = 4,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 16,
                            Amount = 24500m,
                            CarId = 4,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 17,
                            Amount = 140m,
                            CarId = 5,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 18,
                            Amount = 1100m,
                            CarId = 5,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 19,
                            Amount = 7700m,
                            CarId = 5,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 20,
                            Amount = 26000m,
                            CarId = 5,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 21,
                            Amount = 150m,
                            CarId = 6,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 22,
                            Amount = 1150m,
                            CarId = 6,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 23,
                            Amount = 8050m,
                            CarId = 6,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 24,
                            Amount = 27500m,
                            CarId = 6,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 25,
                            Amount = 160m,
                            CarId = 7,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 26,
                            Amount = 1200m,
                            CarId = 7,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 27,
                            Amount = 8400m,
                            CarId = 7,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 28,
                            Amount = 29000m,
                            CarId = 7,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 29,
                            Amount = 170m,
                            CarId = 8,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 30,
                            Amount = 1250m,
                            CarId = 8,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 31,
                            Amount = 8750m,
                            CarId = 8,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 32,
                            Amount = 30500m,
                            CarId = 8,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 33,
                            Amount = 180m,
                            CarId = 9,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 34,
                            Amount = 1300m,
                            CarId = 9,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 35,
                            Amount = 9100m,
                            CarId = 9,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 36,
                            Amount = 32000m,
                            CarId = 9,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 37,
                            Amount = 190m,
                            CarId = 10,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 38,
                            Amount = 1350m,
                            CarId = 10,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 39,
                            Amount = 9450m,
                            CarId = 10,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 40,
                            Amount = 33500m,
                            CarId = 10,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 41,
                            Amount = 200m,
                            CarId = 11,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 42,
                            Amount = 1400m,
                            CarId = 11,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 43,
                            Amount = 9800m,
                            CarId = 11,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 44,
                            Amount = 35000m,
                            CarId = 11,
                            PricingId = 4
                        },
                        new
                        {
                            CarPricingId = 45,
                            Amount = 210m,
                            CarId = 12,
                            PricingId = 1
                        },
                        new
                        {
                            CarPricingId = 46,
                            Amount = 1450m,
                            CarId = 12,
                            PricingId = 2
                        },
                        new
                        {
                            CarPricingId = 47,
                            Amount = 10150m,
                            CarId = 12,
                            PricingId = 3
                        },
                        new
                        {
                            CarPricingId = 48,
                            Amount = 36500m,
                            CarId = 12,
                            PricingId = 4
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Category", b =>
                {
                    b.Property<int>("CategoryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CategoryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CategoryId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            CategoryId = 1,
                            Name = "Hibrit Araçlar"
                        },
                        new
                        {
                            CategoryId = 2,
                            Name = "Araç Bakımları"
                        },
                        new
                        {
                            CategoryId = 3,
                            Name = "Periyodik Muayeneler"
                        },
                        new
                        {
                            CategoryId = 4,
                            Name = "Elektrikli Araçlar"
                        },
                        new
                        {
                            CategoryId = 5,
                            Name = "Araç Temizliği"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Comment", b =>
                {
                    b.Property<int>("CommentId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CommentId"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CommentId");

                    b.HasIndex("BlogId");

                    b.ToTable("Comments");

                    b.HasData(
                        new
                        {
                            CommentId = 1,
                            BlogId = 1,
                            CreatedDate = new DateTime(2023, 6, 16, 10, 20, 0, 0, DateTimeKind.Unspecified),
                            Email = "ahmet.yilmaz@example.com",
                            Name = "Ahmet",
                            Surname = "Yılmaz",
                            Text = "Elektrikli araçlar hakkında çok bilgilendirici bir yazı olmuş."
                        },
                        new
                        {
                            CommentId = 2,
                            BlogId = 2,
                            CreatedDate = new DateTime(2023, 7, 21, 14, 30, 0, 0, DateTimeKind.Unspecified),
                            Email = "mehmet.kaya@example.com",
                            Name = "Mehmet",
                            Surname = "Kaya",
                            Text = "SUV araçları gerçekten çok kullanışlı ve konforlu. Güzel bir yazı."
                        },
                        new
                        {
                            CommentId = 3,
                            BlogId = 3,
                            CreatedDate = new DateTime(2023, 8, 12, 9, 15, 0, 0, DateTimeKind.Unspecified),
                            Email = "ayse.demir@example.com",
                            Name = "Ayşe",
                            Surname = "Demir",
                            Text = "Sedan arabaların konforu gerçekten çok güzel, ancak ben performansı biraz daha yüksek beklerdim."
                        },
                        new
                        {
                            CommentId = 4,
                            BlogId = 4,
                            CreatedDate = new DateTime(2023, 9, 6, 16, 45, 0, 0, DateTimeKind.Unspecified),
                            Email = "fatma.can@example.com",
                            Name = "Fatma",
                            Surname = "Can",
                            Text = "Kamyonlar çok dayanıklı ama şehir içi kullanımda zorlanıyorlar. Güzel yazı."
                        },
                        new
                        {
                            CommentId = 5,
                            BlogId = 1,
                            CreatedDate = new DateTime(2023, 6, 17, 11, 10, 0, 0, DateTimeKind.Unspecified),
                            Email = "ali.sahin@example.com",
                            Name = "Ali",
                            Surname = "Şahin",
                            Text = "Elektrikli araçların geleceği çok parlak görünüyor, yakından takip ediyorum."
                        },
                        new
                        {
                            CommentId = 6,
                            BlogId = 2,
                            CreatedDate = new DateTime(2023, 7, 22, 13, 0, 0, 0, DateTimeKind.Unspecified),
                            Email = "elif.acar@example.com",
                            Name = "Elif",
                            Surname = "Acar",
                            Text = "SUV modellerinin avantajları gerçekten doğru tespit edilmiş, ancak fiyatları biraz yüksek."
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Contact", b =>
                {
                    b.Property<int>("ContactId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ContactId"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("SendDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Subject")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ContactId");

                    b.ToTable("Contacts");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Customer", b =>
                {
                    b.Property<int>("CustomerId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustomerId"));

                    b.Property<string>("CustomerMail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CustomerSurname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("CustomerId");

                    b.ToTable("Customers");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Feature", b =>
                {
                    b.Property<int>("FeatureId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FeatureId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FeatureId");

                    b.ToTable("Features");

                    b.HasData(
                        new
                        {
                            FeatureId = 1,
                            Name = "Klima"
                        },
                        new
                        {
                            FeatureId = 2,
                            Name = "GPS Navigasyon"
                        },
                        new
                        {
                            FeatureId = 3,
                            Name = "Bluetooth Bağlantısı"
                        },
                        new
                        {
                            FeatureId = 4,
                            Name = "Isıtmalı Koltuklar"
                        },
                        new
                        {
                            FeatureId = 5,
                            Name = "Wifi"
                        },
                        new
                        {
                            FeatureId = 6,
                            Name = "Geri Görüş Kamerası"
                        },
                        new
                        {
                            FeatureId = 7,
                            Name = "Hız Sabitleyici"
                        },
                        new
                        {
                            FeatureId = 8,
                            Name = "Park Sensörleri"
                        },
                        new
                        {
                            FeatureId = 9,
                            Name = "Araç Kiti"
                        },
                        new
                        {
                            FeatureId = 10,
                            Name = "Hava Yastığı"
                        },
                        new
                        {
                            FeatureId = 11,
                            Name = "Çocuk Kiliti"
                        },
                        new
                        {
                            FeatureId = 12,
                            Name = "Bebek Koltuğu"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.FooterAddress", b =>
                {
                    b.Property<int>("FooterAddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("FooterAddressId"));

                    b.Property<string>("Address")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("FooterAddressId");

                    b.ToTable("FooterAddresses");

                    b.HasData(
                        new
                        {
                            FooterAddressId = 1,
                            Address = "123 Ana Cadde, Şehir, Ülke",
                            Description = "Merkezi Ofis",
                            Email = "info@AracKiralama.com",
                            Phone = "+90 123 456 7890"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Location", b =>
                {
                    b.Property<int>("LocationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("LocationId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("LocationId");

                    b.ToTable("Locations");

                    b.HasData(
                        new
                        {
                            LocationId = 1,
                            Name = "İstanbul"
                        },
                        new
                        {
                            LocationId = 2,
                            Name = "Ankara"
                        },
                        new
                        {
                            LocationId = 3,
                            Name = "İzmir"
                        },
                        new
                        {
                            LocationId = 4,
                            Name = "Bursa"
                        },
                        new
                        {
                            LocationId = 5,
                            Name = "Antalya"
                        },
                        new
                        {
                            LocationId = 6,
                            Name = "Adana"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Pricing", b =>
                {
                    b.Property<int>("PricingId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PricingId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PricingId");

                    b.ToTable("Pricings");

                    b.HasData(
                        new
                        {
                            PricingId = 1,
                            Name = "Saatlik"
                        },
                        new
                        {
                            PricingId = 2,
                            Name = "Günlük"
                        },
                        new
                        {
                            PricingId = 3,
                            Name = "Haftalık"
                        },
                        new
                        {
                            PricingId = 4,
                            Name = "Aylık"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.RentACar", b =>
                {
                    b.Property<int>("RentACarId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentACarId"));

                    b.Property<bool>("Available")
                        .HasColumnType("bit");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("LocationId")
                        .HasColumnType("int");

                    b.HasKey("RentACarId");

                    b.HasIndex("CarId");

                    b.HasIndex("LocationId");

                    b.ToTable("RentACars");

                    b.HasData(
                        new
                        {
                            RentACarId = 1,
                            Available = true,
                            CarId = 1,
                            LocationId = 1
                        },
                        new
                        {
                            RentACarId = 2,
                            Available = false,
                            CarId = 2,
                            LocationId = 2
                        },
                        new
                        {
                            RentACarId = 3,
                            Available = true,
                            CarId = 3,
                            LocationId = 3
                        },
                        new
                        {
                            RentACarId = 4,
                            Available = false,
                            CarId = 4,
                            LocationId = 4
                        },
                        new
                        {
                            RentACarId = 5,
                            Available = true,
                            CarId = 5,
                            LocationId = 5
                        },
                        new
                        {
                            RentACarId = 6,
                            Available = true,
                            CarId = 6,
                            LocationId = 6
                        },
                        new
                        {
                            RentACarId = 7,
                            Available = true,
                            CarId = 7,
                            LocationId = 1
                        },
                        new
                        {
                            RentACarId = 8,
                            Available = false,
                            CarId = 8,
                            LocationId = 2
                        },
                        new
                        {
                            RentACarId = 9,
                            Available = true,
                            CarId = 9,
                            LocationId = 3
                        },
                        new
                        {
                            RentACarId = 10,
                            Available = true,
                            CarId = 10,
                            LocationId = 4
                        },
                        new
                        {
                            RentACarId = 11,
                            Available = true,
                            CarId = 11,
                            LocationId = 5
                        },
                        new
                        {
                            RentACarId = 12,
                            Available = true,
                            CarId = 12,
                            LocationId = 6
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.RentACarProcess", b =>
                {
                    b.Property<int>("RentACarProcessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("RentACarProcessId"));

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<int>("CustomerId")
                        .HasColumnType("int");

                    b.Property<DateTime>("DropOffDate")
                        .HasColumnType("Date");

                    b.Property<string>("DropOffDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DropOffLocation")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("DropOffTime")
                        .HasColumnType("time");

                    b.Property<DateTime>("PickUpDate")
                        .HasColumnType("Date");

                    b.Property<string>("PickUpDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("PickUpLocation")
                        .HasColumnType("int");

                    b.Property<TimeSpan>("PickUpTime")
                        .HasColumnType("time");

                    b.Property<decimal>("TotalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("RentACarProcessId");

                    b.HasIndex("CarId");

                    b.HasIndex("CustomerId");

                    b.ToTable("RentACarProcesses");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Reservation", b =>
                {
                    b.Property<int>("ReservationId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationId"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<int>("CarId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("DriverLicenseYear")
                        .HasColumnType("int");

                    b.Property<int?>("DropOffLocationId")
                        .HasColumnType("int");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Phone")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PickUpLocationId")
                        .HasColumnType("int");

                    b.Property<int>("ReservationStatusId")
                        .HasColumnType("int");

                    b.Property<string>("Surname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationId");

                    b.HasIndex("CarId");

                    b.HasIndex("DropOffLocationId");

                    b.HasIndex("PickUpLocationId");

                    b.HasIndex("ReservationStatusId");

                    b.ToTable("Reservations");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.ReservationStatus", b =>
                {
                    b.Property<int>("ReservationStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ReservationStatusId"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ReservationStatusId");

                    b.ToTable("ReservationStatuses");

                    b.HasData(
                        new
                        {
                            ReservationStatusId = 1,
                            Icon = "fa-clock",
                            Name = "Beklemede"
                        },
                        new
                        {
                            ReservationStatusId = 2,
                            Icon = "fa-check-circle",
                            Name = "Onaylandı"
                        },
                        new
                        {
                            ReservationStatusId = 3,
                            Icon = "fa-times-circle",
                            Name = "İptal Edildi"
                        },
                        new
                        {
                            ReservationStatusId = 4,
                            Icon = "fa-check-square",
                            Name = "Tamamlandı"
                        },
                        new
                        {
                            ReservationStatusId = 5,
                            Icon = "fa-car",
                            Name = "Teslimat Sürecinde"
                        },
                        new
                        {
                            ReservationStatusId = 6,
                            Icon = "fa-ban",
                            Name = "Reddedildi"
                        },
                        new
                        {
                            ReservationStatusId = 7,
                            Icon = "fa-money-bill",
                            Name = "Ödeme Bekleniyor"
                        },
                        new
                        {
                            ReservationStatusId = 8,
                            Icon = "fa-map-marker-alt",
                            Name = "Teslimat Bekleniyor"
                        },
                        new
                        {
                            ReservationStatusId = 9,
                            Icon = "fa-user-slash",
                            Name = "Gelmedi"
                        },
                        new
                        {
                            ReservationStatusId = 10,
                            Icon = "fa-undo",
                            Name = "Ücret İade Edildi"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IconUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ServiceId");

                    b.ToTable("Services");

                    b.HasData(
                        new
                        {
                            ServiceId = 1,
                            Description = "Düğün gününüzü unutulmaz kılmak için profesyonel ve kapsamlı düğün organizasyonu hizmetleri sunuyoruz.",
                            IconUrl = "flaticon-wedding-car",
                            Title = "Düğün Organizasyonu"
                        },
                        new
                        {
                            ServiceId = 2,
                            Description = "Şehir turlarınızın unutulmaz olması için profesyonel ve kapsamlı hizmetler sunuyoruz.",
                            IconUrl = "flaticon-transportation",
                            Title = "Şehir Turları"
                        },
                        new
                        {
                            ServiceId = 3,
                            Description = "VIP servislerimiz ile özel anlarınızı unutulmaz kılmak için profesyonel ve kapsamlı hizmetler sunuyoruz.",
                            IconUrl = "flaticon-car",
                            Title = "VIP Servis"
                        },
                        new
                        {
                            ServiceId = 4,
                            Description = "Havalimanı aktarmalarınız için profesyonel ve güvenilir VIP servisler sunuyoruz.",
                            IconUrl = "flaticon-rent",
                            Title = "Havalimanı Aktarmaları"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.SocialMedia", b =>
                {
                    b.Property<int>("SocialMediaId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("SocialMediaId"));

                    b.Property<string>("Icon")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("SocialMediaId");

                    b.ToTable("SocialMedias");

                    b.HasData(
                        new
                        {
                            SocialMediaId = 1,
                            Icon = "fab fa-facebook",
                            Name = "Facebook",
                            Url = "https://www.facebook.com"
                        },
                        new
                        {
                            SocialMediaId = 2,
                            Icon = "fab fa-twitter",
                            Name = "Twitter",
                            Url = "https://www.twitter.com"
                        },
                        new
                        {
                            SocialMediaId = 3,
                            Icon = "fab fa-instagram",
                            Name = "Instagram",
                            Url = "https://www.instagram.com"
                        },
                        new
                        {
                            SocialMediaId = 4,
                            Icon = "fab fa-linkedin",
                            Name = "LinkedIn",
                            Url = "https://www.linkedin.com"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.TagCloud", b =>
                {
                    b.Property<int>("TagCloudId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TagCloudId"));

                    b.Property<int>("BlogId")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TagCloudId");

                    b.HasIndex("BlogId");

                    b.ToTable("TagClouds");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Testimonial", b =>
                {
                    b.Property<int>("TestimonialId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("TestimonialId"));

                    b.Property<string>("Comment")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("TestimonialId");

                    b.ToTable("Testimonials");

                    b.HasData(
                        new
                        {
                            TestimonialId = 1,
                            Comment = "Proje Yöneticisi, projelerin zamanında, bütçeye uygun ve kaliteye uygun tamamlanmasını sağlar, ekipleri yönetir ve kaynakları etkin kullanır.",
                            ImageUrl = "/carbook-master/images/person_1.jpg",
                            Name = "Semih Sarı",
                            Title = "Proje Yöneticisi"
                        },
                        new
                        {
                            TestimonialId = 2,
                            Comment = "Endüstri Mühendisi, üretim süreçlerini ve kaynakları en verimli şekilde düzenleyerek verimliliği artıran ve maliyetleri düşüren bir profesyoneldir.",
                            ImageUrl = "/carbook-master/images/person_2.jpg",
                            Name = "Ahmet Öztürk",
                            Title = "Endüstri Mühendisi"
                        },
                        new
                        {
                            TestimonialId = 3,
                            Comment = "Makine Mühendisi, mekanik sistemlerin tasarım, üretim ve bakım süreçlerini yöneterek verimliliği artıran ve teknik çözümler üreten uzmandır.",
                            ImageUrl = "/carbook-master/images/person_3.jpg",
                            Name = "Mehmet Ali Yıldız",
                            Title = "Makine Mühendisi"
                        },
                        new
                        {
                            TestimonialId = 4,
                            Comment = "Bilgisayar Mühendisi, yazılım ve donanım sistemlerini tasarlayan, geliştiren ve optimize eden, teknoloji çözümleri üreten uzmandır.",
                            ImageUrl = "/carbook-master/images/person_4.jpg",
                            Name = "Eyyüp Acar",
                            Title = "Bilgisayar Mühendisi"
                        });
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Blog", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Author", "Author")
                        .WithMany("Blogs")
                        .HasForeignKey("AuthorID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBook.Domain.Entities.Category", "Category")
                        .WithMany("Blogs")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Author");

                    b.Navigation("Category");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Car", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Brand", "Brand")
                        .WithMany("Cars")
                        .HasForeignKey("BrandId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Brand");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.CarDescription", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Car", "Car")
                        .WithMany("CarDescriptions")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.CarFeature", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Car", "Car")
                        .WithMany("CarFeatures")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBook.Domain.Entities.Feature", "Feature")
                        .WithMany("CarFeatures")
                        .HasForeignKey("FeatureId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Feature");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.CarPricing", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Car", "Car")
                        .WithMany("CarPricings")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBook.Domain.Entities.Pricing", "Pricing")
                        .WithMany("CarPricings")
                        .HasForeignKey("PricingId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Pricing");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Comment", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Blog", "Blog")
                        .WithMany("Comments")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.RentACar", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Car", "Car")
                        .WithMany("RentACars")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBook.Domain.Entities.Location", "Location")
                        .WithMany("RentACars")
                        .HasForeignKey("LocationId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Location");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.RentACarProcess", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Car", "Car")
                        .WithMany()
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBook.Domain.Entities.Customer", "Customer")
                        .WithMany("RentACarProcesses")
                        .HasForeignKey("CustomerId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("Customer");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Reservation", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Car", "Car")
                        .WithMany("Reservations")
                        .HasForeignKey("CarId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("CarBook.Domain.Entities.Location", "DropOffLocation")
                        .WithMany("DropOffReservation")
                        .HasForeignKey("DropOffLocationId");

                    b.HasOne("CarBook.Domain.Entities.Location", "PickUpLocation")
                        .WithMany("PickUpReservation")
                        .HasForeignKey("PickUpLocationId");

                    b.HasOne("CarBook.Domain.Entities.ReservationStatus", "ReservationStatus")
                        .WithMany("Reservations")
                        .HasForeignKey("ReservationStatusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Car");

                    b.Navigation("DropOffLocation");

                    b.Navigation("PickUpLocation");

                    b.Navigation("ReservationStatus");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.TagCloud", b =>
                {
                    b.HasOne("CarBook.Domain.Entities.Blog", "Blog")
                        .WithMany("TagClouds")
                        .HasForeignKey("BlogId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Blog");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Author", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Blog", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("TagClouds");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Brand", b =>
                {
                    b.Navigation("Cars");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Car", b =>
                {
                    b.Navigation("CarDescriptions");

                    b.Navigation("CarFeatures");

                    b.Navigation("CarPricings");

                    b.Navigation("RentACars");

                    b.Navigation("Reservations");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Category", b =>
                {
                    b.Navigation("Blogs");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Customer", b =>
                {
                    b.Navigation("RentACarProcesses");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Feature", b =>
                {
                    b.Navigation("CarFeatures");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Location", b =>
                {
                    b.Navigation("DropOffReservation");

                    b.Navigation("PickUpReservation");

                    b.Navigation("RentACars");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.Pricing", b =>
                {
                    b.Navigation("CarPricings");
                });

            modelBuilder.Entity("CarBook.Domain.Entities.ReservationStatus", b =>
                {
                    b.Navigation("Reservations");
                });
#pragma warning restore 612, 618
        }
    }
}
